import { Inject, Injectable, Logger, type OnModuleInit } from '@nestjs/common';
import {
  DeleteObjectCommand,
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { createReadStream } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';
import type { Readable } from 'node:stream';
import { CONFIG_TOKEN, type AppConfig } from '../config/env';

export interface StoredObject {
  key: string;
  size: number;
}

/**
 * Storage abstraction with a local-disk driver for development and an
 * S3-compatible driver for production (AWS S3, Cloudflare R2, MinIO).
 *
 * Keys are always generated by the application (`{workspaceId}/{taskId}/{uuid}{ext}`),
 * never derived from the uploaded filename, which makes path traversal
 * structurally impossible rather than something we have to sanitise our way out of.
 */
@Injectable()
export class StorageService implements OnModuleInit {
  private readonly logger = new Logger(StorageService.name);
  private s3: S3Client | null = null;
  private readonly localRoot: string;

  constructor(@Inject(CONFIG_TOKEN) private readonly config: AppConfig) {
    this.localRoot = resolve(process.cwd(), config.STORAGE_LOCAL_DIR);
  }

  async onModuleInit(): Promise<void> {
    if (this.config.STORAGE_DRIVER === 's3') {
      this.s3 = new S3Client({
        region: this.config.S3_REGION as string,
        ...(this.config.S3_ENDPOINT ? { endpoint: this.config.S3_ENDPOINT } : {}),
        forcePathStyle: this.config.S3_FORCE_PATH_STYLE,
        credentials: {
          accessKeyId: this.config.S3_ACCESS_KEY_ID as string,
          secretAccessKey: this.config.S3_SECRET_ACCESS_KEY as string,
        },
      });
      this.logger.log(`Storage driver: s3 (bucket ${this.config.S3_BUCKET})`);
      return;
    }

    await mkdir(this.localRoot, { recursive: true });
    this.logger.log(`Storage driver: local (${this.localRoot})`);
  }

  async put(key: string, body: Buffer, contentType: string): Promise<StoredObject> {
    if (this.s3) {
      await this.s3.send(
        new PutObjectCommand({
          Bucket: this.config.S3_BUCKET as string,
          Key: key,
          Body: body,
          ContentType: contentType,
        }),
      );
      return { key, size: body.byteLength };
    }

    const path = this.localPath(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
    return { key, size: body.byteLength };
  }

  async getStream(key: string): Promise<Readable> {
    if (this.s3) {
      const result = await this.s3.send(
        new GetObjectCommand({ Bucket: this.config.S3_BUCKET as string, Key: key }),
      );
      return result.Body as Readable;
    }
    return createReadStream(this.localPath(key));
  }

  async delete(key: string): Promise<void> {
    if (this.s3) {
      await this.s3.send(
        new DeleteObjectCommand({ Bucket: this.config.S3_BUCKET as string, Key: key }),
      );
      return;
    }
    await rm(this.localPath(key), { force: true });
  }

  /**
   * Short-lived direct link, available only on S3. The local driver returns null
   * and downloads go through the authorised API route instead.
   */
  async signedUrl(key: string, ttlSeconds = 300): Promise<string | null> {
    if (!this.s3) return null;
    return getSignedUrl(
      this.s3,
      new GetObjectCommand({ Bucket: this.config.S3_BUCKET as string, Key: key }),
      { expiresIn: ttlSeconds },
    );
  }

  /** Belt-and-braces: even a generated key is re-checked against escaping the root. */
  private localPath(key: string): string {
    const path = normalize(join(this.localRoot, key));
    if (!path.startsWith(this.localRoot + sep)) {
      throw new Error('Resolved storage path escapes the storage root');
    }
    return path;
  }
}
